// Generated by gencpp from file ros_wrapper/State.msg
// DO NOT EDIT!


#ifndef ROS_WRAPPER_MESSAGE_STATE_H
#define ROS_WRAPPER_MESSAGE_STATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_wrapper
{
template <class ContainerAllocator>
struct State_
{
  typedef State_<ContainerAllocator> Type;

  State_()
    : battery(0)
    , height(0.0)
    , temperature(0.0)  {
    }
  State_(const ContainerAllocator& _alloc)
    : battery(0)
    , height(0.0)
    , temperature(0.0)  {
  (void)_alloc;
    }



   typedef int64_t _battery_type;
  _battery_type battery;

   typedef float _height_type;
  _height_type height;

   typedef float _temperature_type;
  _temperature_type temperature;





  typedef boost::shared_ptr< ::ros_wrapper::State_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_wrapper::State_<ContainerAllocator> const> ConstPtr;

}; // struct State_

typedef ::ros_wrapper::State_<std::allocator<void> > State;

typedef boost::shared_ptr< ::ros_wrapper::State > StatePtr;
typedef boost::shared_ptr< ::ros_wrapper::State const> StateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_wrapper::State_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_wrapper::State_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_wrapper::State_<ContainerAllocator1> & lhs, const ::ros_wrapper::State_<ContainerAllocator2> & rhs)
{
  return lhs.battery == rhs.battery &&
    lhs.height == rhs.height &&
    lhs.temperature == rhs.temperature;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_wrapper::State_<ContainerAllocator1> & lhs, const ::ros_wrapper::State_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_wrapper

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_wrapper::State_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_wrapper::State_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_wrapper::State_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_wrapper::State_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_wrapper::State_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_wrapper::State_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_wrapper::State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b00fd2063ed0650cb18a14280f6436f2";
  }

  static const char* value(const ::ros_wrapper::State_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb00fd2063ed0650cULL;
  static const uint64_t static_value2 = 0xb18a14280f6436f2ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_wrapper::State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_wrapper/State";
  }

  static const char* value(const ::ros_wrapper::State_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_wrapper::State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 battery\n"
"float32 height\n"
"float32 temperature\n"
;
  }

  static const char* value(const ::ros_wrapper::State_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_wrapper::State_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.battery);
      stream.next(m.height);
      stream.next(m.temperature);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct State_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_wrapper::State_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_wrapper::State_<ContainerAllocator>& v)
  {
    s << indent << "battery: ";
    Printer<int64_t>::stream(s, indent + "  ", v.battery);
    s << indent << "height: ";
    Printer<float>::stream(s, indent + "  ", v.height);
    s << indent << "temperature: ";
    Printer<float>::stream(s, indent + "  ", v.temperature);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_WRAPPER_MESSAGE_STATE_H
